# onboarding.py — First-run setup
#
# Shows a tkinter GUI on Raspberry Pi OS desktop.
# Falls back to terminal prompts if running headless or tkinter is unavailable.
#
# Called by agent.py when no .env file is found.

import os
import stat
from pathlib import Path

import config

ENV_FILE = Path(__file__).parent / ".env"


def write_env(api_key: str, model: str, telegram_token: str,
              allowed_users: str = "", chat_id: str = "") -> None:
    """
    Write the .env configuration file.
    Sets file permissions to 600 (owner read/write only).
    """
    content = f"""# MolluskAI Configuration
# This file was generated by the onboarding setup.
# Do not share or commit this file — it contains your API keys.

OPENROUTER_API_KEY={api_key}
OPENROUTER_MODEL={model}
TELEGRAM_TOKEN={telegram_token}
TELEGRAM_ALLOWED_USERS={allowed_users}
TELEGRAM_CHAT_ID={chat_id}
"""
    ENV_FILE.write_text(content)
    # Restrict to owner read/write only (equivalent to chmod 600)
    os.chmod(ENV_FILE, stat.S_IRUSR | stat.S_IWUSR)
    print(f"[onboarding] Configuration saved to {ENV_FILE}")


def run() -> None:
    """
    Run first-time setup. Tries the GUI, falls back to terminal prompts.
    Blocks until setup is complete and .env is written.
    """
    try:
        _run_gui()
    except Exception:
        # tkinter not available, no display, or any other GUI error
        _run_terminal()


# ---------------------------------------------------------------------------
# GUI onboarding (tkinter)
# ---------------------------------------------------------------------------

def _run_gui() -> None:
    """Show the setup window. Raises an exception if tkinter is unavailable."""
    import tkinter as tk
    from tkinter import ttk, messagebox

    root = tk.Tk()
    root.title("MolluskAI Setup")
    root.resizable(False, False)

    # Centre the window on screen
    root.update_idletasks()
    w, h = 520, 400
    x = (root.winfo_screenwidth()  - w) // 2
    y = (root.winfo_screenheight() - h) // 2
    root.geometry(f"{w}x{h}+{x}+{y}")

    pad = {"padx": 12, "pady": 5}

    tk.Label(
        root,
        text="MolluskAI Setup",
        font=("TkDefaultFont", 15, "bold"),
    ).pack(pady=(18, 2))
    tk.Label(
        root,
        text="Enter your credentials to get started.",
        fg="grey",
    ).pack(pady=(0, 10))

    frame = tk.Frame(root)
    frame.pack(fill="both", expand=True, padx=28, pady=4)

    def row(label_text, row_num, show=None, width=36):
        tk.Label(frame, text=label_text, anchor="w").grid(
            row=row_num, column=0, sticky="w", **pad
        )
        var = tk.StringVar()
        entry_kwargs = {"textvariable": var, "width": width}
        if show:
            entry_kwargs["show"] = show
        tk.Entry(frame, **entry_kwargs).grid(row=row_num, column=1, **pad)
        return var

    api_key_var  = row("OpenRouter API Key:",    0, show="*")
    tg_token_var = row("Telegram Bot Token:",    2)
    tg_users_var = row("Allowed Telegram IDs:",  3)
    tg_chat_var  = row("Telegram Chat ID:",      4)

    tk.Label(
        frame,
        text="(IDs from @userinfobot — comma-separated for multiple users)",
        fg="grey",
        font=("TkDefaultFont", 8),
    ).grid(row=5, column=1, sticky="w", padx=12)

    # Model selector
    tk.Label(frame, text="Model:", anchor="w").grid(row=1, column=0, sticky="w", **pad)
    model_var = tk.StringVar(value=config.POPULAR_MODELS[0])
    model_combo = ttk.Combobox(
        frame, textvariable=model_var, values=config.POPULAR_MODELS, width=34
    )
    model_combo.grid(row=1, column=1, sticky="w", **pad)

    def fetch_models():
        """Fetch live model list from OpenRouter and populate the dropdown."""
        try:
            import llm
            models = llm.get_models()
            model_combo["values"] = models
            messagebox.showinfo("Done", f"Loaded {len(models)} models from OpenRouter.")
        except Exception as e:
            messagebox.showwarning("Error", f"Could not fetch models: {e}\nUsing default list.")

    tk.Button(
        frame, text="Fetch models from OpenRouter", command=fetch_models
    ).grid(row=1, column=1, sticky="e", padx=12)

    def save_and_start():
        if not api_key_var.get().strip():
            messagebox.showwarning("Missing field", "Please enter your OpenRouter API Key.")
            return
        write_env(
            api_key_var.get().strip(),
            model_var.get().strip(),
            tg_token_var.get().strip(),
            tg_users_var.get().strip(),
            tg_chat_var.get().strip(),
        )
        root.destroy()

    tk.Button(
        root,
        text="Save & Start",
        command=save_and_start,
        bg="#4a90d9",
        fg="white",
        font=("TkDefaultFont", 11),
        padx=16,
        pady=4,
    ).pack(pady=14)

    root.mainloop()

    # If the window was closed without saving, exit gracefully
    if not config.is_configured():
        raise SystemExit("Setup cancelled.")


# ---------------------------------------------------------------------------
# Terminal onboarding (headless fallback)
# ---------------------------------------------------------------------------

def _run_terminal() -> None:
    """Interactive terminal setup for headless or SSH installs."""
    print("\n" + "=" * 50)
    print("  MolluskAI — First-time Setup")
    print("=" * 50 + "\n")
    print("No configuration found. Let's set you up.\n")

    # API Key
    api_key = input("OpenRouter API Key: ").strip()
    if not api_key:
        print("API key is required. Exiting.")
        raise SystemExit(1)

    # Model selection
    print("\nAvailable models:")
    for i, m in enumerate(config.POPULAR_MODELS, 1):
        print(f"  {i:2}. {m}")
    choice = input(
        f"\nSelect a number [1-{len(config.POPULAR_MODELS)}] or type a model ID: "
    ).strip()
    if choice.isdigit() and 1 <= int(choice) <= len(config.POPULAR_MODELS):
        model = config.POPULAR_MODELS[int(choice) - 1]
    elif choice:
        model = choice
    else:
        model = config.POPULAR_MODELS[0]

    # Telegram
    print("\n--- Telegram (optional, press Enter to skip) ---")
    tg_token = input("Telegram Bot Token: ").strip()
    tg_users = ""
    tg_chat  = ""
    if tg_token:
        tg_users = input(
            "Allowed Telegram User IDs (comma-separated, find via @userinfobot): "
        ).strip()
        tg_chat = input(
            "Telegram Chat ID for outbound notifications (usually same as your user ID): "
        ).strip()

    write_env(api_key, model, tg_token, tg_users, tg_chat)
    print("\nSetup complete. Starting MolluskAI...\n")
